import = [
  "~/.config/alacritty/theme/themes/nordic.toml"
]

[window]
dynamic_padding = false
title = "Terminal"
opacity = 0.9
blur = true
startup_mode = "Maximized"
decorations = "Buttonless"
  [window.padding]
  x = 10
  y = 10

  [window.class]
  instance = "Alacritty"
  general = "Alacritty"

[scrolling]
history = 5_000


[font]
size = 12

  [font.normal]
  family = "MonaspiceXe Nerd Font Propo"
  style = "Bold"

  [font.bold]
  family = "MonaspiceXe Nerd Font Propo"
  style = "Bold"

  [font.italic]
  family = "MonaspiceXe Nerd Font Propo"
  style = "SemiBold Italic"

  [font.bold_italic]
  family = "MonaspiceXe Nerd Font Propo"
  style = "Bold Italic"

[shell]
args = ["new-session", "-A", "-D", "-s", "main"]
program = "/opt/homebrew/bin/tmux"

[debug]
log_level = "DEBUG"

[[keyboard.bindings]]
chars = "\u0000c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000p"
key = "["
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000n"
key = "]"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001e"
key = "6"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Command|Shift"
